name: CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - next
      - '+([0-9])?(.{+([0-9]),x}).x'

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  lint-test-build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      # - if: false  
      #   # Disabled until tests are implemented
      #   name: Unit Tests
      #   run: npm run test:unit
        
      - name: Build
        run: npm run build

      # - if: false 
      #   # Disabled until tests are implemented
      #   name: E2E Tests
      #   run: npm run test:e2e
        
      - name: Release
        # currently this causes a second build due to the prepublishOnly script. 
        # that's okay we want that to happen to prevent publishing stale local builds.
        # we should maybe look for a way to set an ENV var to skip the build in CI
        # if performance becomes an issue.
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
